defmodule Tymeslot.Security.FieldValidators.TLDList do
  @moduledoc """
  Domain ending validation, typo correction, and TLD lookups.

  Loads TLD data from `priv/tlds.json` at compile time into MapSets for O(1)
  lookups. An ending absent from that file is rejected, so the file's accuracy
  is what stands between a real address and a refused booking.

  ## Keeping the list honest

  The `delegated` list is IANA's, regenerated by `mix tymeslot.sync_tlds` and
  never edited by hand. Three years of hand maintenance left it missing six
  delegated endings (`.homes` among them, which cost a self-hosted user their
  bookings, issue #83) while carrying 98 that ICANN has never delegated or has
  since retired, so the fetch replaces the judgement rather than supplementing
  it. `TldFreshnessTest` fails nightly once the shipped copy drifts from IANA.

  Two consequences of gating on a snapshot are worth stating plainly, because
  neither is fixable from inside this module:

    * **A release freezes the list for every self-hosted instance** until it
      upgrades. Running the sync before cutting a release is therefore not
      housekeeping; it is the only moment the list gets refreshed for the
      people running it.
    * **A newly delegated ending is refused until the next release reaches the
      instance.** The message for a well-formed but unknown ending says exactly
      that, rather than telling the user their address is invalid, because the
      likelier fault by then is ours.

  The remaining three lists are curated by hand and documented on the sync task.
  """

  @tld_json_path Path.join([__DIR__, "../../../../priv/tlds.json"])
  @external_resource @tld_json_path

  @tld_data @tld_json_path |> File.read!() |> JSON.decode!()

  @common_tlds MapSet.new(@tld_data["tlds"]["common"])

  @special_use_tlds MapSet.new(@tld_data["tlds"]["special_use"])

  # `special_use` is subtracted rather than merely left out: `arpa` is both
  # delegated by IANA and reserved, and reserved has to win.
  @public_tlds @tld_data["tlds"]
               |> Map.take(["delegated", "second_level"])
               |> Map.values()
               |> List.flatten()
               |> MapSet.new()
               |> MapSet.difference(@special_use_tlds)

  # Endings that are not delegated TLDs and are overwhelmingly a mistyped
  # common ending. Verified against IANA's delegated list; an entry may only be
  # added once confirmed absent from it, and must be removed if ICANN ever
  # delegates it. The compile-time guard below catches the half of that
  # invariant the shipped data can answer on its own.
  @typo_corrections %{
    "cim" => "com",
    "cmo" => "com",
    "comm" => "com",
    "con" => "com",
    "coom" => "com",
    "cpm" => "com",
    "ocm" => "com",
    "vom" => "com",
    "xom" => "com",
    "ner" => "net",
    "nte" => "net",
    "ogr" => "org",
    "orh" => "org",
    "rog" => "org"
  }

  # A typo entry that is also a known TLD would resurrect the bug this design
  # exists to prevent, so the collision fails the build rather than waiting to
  # be noticed in production.
  @known_endings MapSet.union(@public_tlds, @special_use_tlds)
  @colliding_typos Enum.filter(Map.keys(@typo_corrections), &MapSet.member?(@known_endings, &1))

  if @colliding_typos != [] do
    raise "@typo_corrections entries are known endings and would be misreported: " <>
            Enum.join(@colliding_typos, ", ")
  end

  # A well-formed ending is either a Unicode U-label of two or more letters
  # (digits and hyphens never appear in a TLD) or a punycode A-label. 63 is the
  # DNS label limit.
  @u_label ~r/^\p{L}{2,63}$/u
  @a_label ~r/^xn--[a-z0-9]+(?:-[a-z0-9]+)*$/

  @doc """
  Returns `true` if the given TLD is a known public TLD, `false` otherwise.

  Special-use TLDs (localhost, test, local, onion, etc.) are excluded.
  Comparison is case-insensitive.
  """
  @spec valid_public_tld?(String.t()) :: boolean()
  def valid_public_tld?(tld) when is_binary(tld) do
    MapSet.member?(@public_tlds, String.downcase(tld))
  end

  @doc """
  Returns every ending the validator accepts, sorted.

  Exposed for `TldFreshnessTest`, which diffs it against IANA to catch the
  snapshot drifting in the direction absence-checking cannot see: endings we
  still accept that have been retired.
  """
  @spec public_tlds() :: [String.t()]
  def public_tlds, do: Enum.sort(@public_tlds)

  @doc """
  Extracts the TLD from a domain string.

  For domains like "company.co.uk", checks if the last two parts form
  a known second-level TLD (e.g. "co.uk"). If so, returns that.
  Otherwise returns just the last part (e.g. "com").

  Comparison is case-insensitive; result is always lowercase.
  """
  @spec extract_tld(String.t()) :: String.t()
  def extract_tld(domain) when is_binary(domain) do
    parts = domain |> String.downcase() |> String.split(".")

    if length(parts) >= 2 do
      two_part = parts |> Enum.take(-2) |> Enum.join(".")

      if MapSet.member?(@public_tlds, two_part) do
        two_part
      else
        List.last(parts)
      end
    else
      List.last(parts)
    end
  end

  @doc """
  Validates the domain ending extracted from a domain string.

  Returns `:ok` only for an ending in `priv/tlds.json`. Everything else is
  rejected, with a message chosen to match the likeliest cause:

    * a reserved special-use ending (`localhost`, `invalid`, `arpa`, …);
    * a known mistyping from `@typo_corrections`, named with its correction;
    * an ending that cannot be a TLD at all (digits, stray hyphens, one
      character), reported as invalid;
    * a well-formed ending we simply do not have, reported as unrecognised and
      possibly newer than this release, since that is the likelier fault.

  The `label` parameter (e.g. `"Email"`, `"Domain"`) is used in the message.
  """
  @spec validate_tld(String.t(), String.t()) :: :ok | {:error, String.t()}
  def validate_tld(tld, label) when is_binary(tld) and is_binary(label) do
    tld_down = String.downcase(tld)

    cond do
      valid_public_tld?(tld_down) ->
        :ok

      MapSet.member?(@special_use_tlds, tld_down) ->
        {:error, "#{label} has a reserved domain ending (.#{tld})"}

      Map.has_key?(@typo_corrections, tld_down) ->
        {:error, typo_message(tld, @typo_corrections[tld_down], label)}

      well_formed_tld?(tld_down) ->
        {:error, unknown_message(tld, tld_down, label)}

      true ->
        {:error, malformed_message(tld, tld_down, label)}
    end
  end

  defp typo_message(tld, correction, label) do
    "#{label} has an unrecognised domain ending (.#{tld}) — did you mean .#{correction}?"
  end

  # Reached only by an ending that looks exactly like a TLD and is not one we
  # know, which is what a domain delegated since this release looks like. The
  # wording says so rather than calling the address invalid.
  defp unknown_message(tld, tld_down, label) do
    case suggest_tld(tld_down) do
      {:ok, suggestion} ->
        "#{label} has an unrecognised domain ending (.#{tld}) — did you mean .#{suggestion}?"

      :no_suggestion ->
        "#{label} has an unrecognised domain ending (.#{tld}). If it is correct, " <>
          "this version of Tymeslot predates it and needs updating."
    end
  end

  defp malformed_message(tld, tld_down, label) do
    case suggest_tld(tld_down) do
      {:ok, suggestion} ->
        "#{label} has an invalid domain ending (.#{tld}) — did you mean .#{suggestion}?"

      :no_suggestion ->
        "#{label} has an invalid domain ending (.#{tld})"
    end
  end

  # Only the final label decides: a two-part ending reaches here solely when it
  # matched the second-level list above, so anything left is `sub.tld` shaped.
  defp well_formed_tld?(tld) do
    last_label = tld |> String.split(".") |> List.last()

    Regex.match?(@u_label, last_label) or Regex.match?(@a_label, last_label)
  end

  @doc """
  Suggests a valid TLD for a likely typo.

  Returns `{:ok, suggestion}` when exactly one plausible candidate is found
  within edit distance 2. Returns `:no_suggestion` when the input is already
  valid, no candidates exist within range, or the candidates are too ambiguous
  to make a confident recommendation.
  """
  @spec suggest_tld(String.t()) :: {:ok, String.t()} | :no_suggestion
  def suggest_tld(tld) when is_binary(tld) do
    tld_down = String.downcase(tld)

    if valid_public_tld?(tld_down) do
      :no_suggestion
    else
      find_suggestion(tld_down)
    end
  end

  defp find_suggestion(typo) do
    candidates =
      @public_tlds
      |> Enum.map(fn tld -> {tld, dl_distance(typo, tld), MapSet.member?(@common_tlds, tld)} end)
      |> Enum.filter(fn {_tld, dist, _is_common} -> dist <= 2 end)
      |> Enum.sort_by(fn {tld, dist, is_common} ->
        {dist, !is_common, abs(String.length(tld) - String.length(typo)), tld}
      end)

    case candidates do
      [] ->
        :no_suggestion

      [{best_tld, best_dist, _is_common} | _rest] ->
        resolve_candidate(candidates, best_tld, best_dist)
    end
  end

  defp resolve_candidate(candidates, best_tld, best_dist) do
    total_at_best = Enum.count(candidates, fn {_tld, dist, _is_common} -> dist == best_dist end)
    common_at_best = Enum.count(candidates, fn {_tld, dist, c} -> dist == best_dist and c end)

    cond do
      total_at_best == 1 -> {:ok, best_tld}
      common_at_best == 1 -> {:ok, find_common_at_dist(candidates, best_dist)}
      total_at_best <= 3 -> {:ok, best_tld}
      true -> :no_suggestion
    end
  end

  defp find_common_at_dist(candidates, dist) do
    {tld, _dist, _is_common} =
      Enum.find(candidates, fn {_tld, d, common?} -> d == dist and common? end)

    tld
  end

  # Damerau-Levenshtein distance (optimal string alignment variant).
  # Counts insertions, deletions, substitutions, and adjacent transpositions
  # each as a single operation.
  defp dl_distance(s, t) do
    s_chars = String.graphemes(s)
    t_chars = String.graphemes(t)
    s_len = length(s_chars)
    t_len = length(t_chars)

    cond do
      s_len == 0 -> t_len
      t_len == 0 -> s_len
      true -> dl_matrix(s_chars, t_chars, s_len, t_len)
    end
  end

  defp dl_matrix(s_chars, t_chars, s_len, t_len) do
    initial = dl_init_matrix(s_len, t_len)

    result =
      Enum.reduce(1..s_len, initial, fn i, d ->
        Enum.reduce(1..t_len, d, fn j, d ->
          put_in(d[i][j], dl_cell(d, s_chars, t_chars, i, j))
        end)
      end)

    result[s_len][t_len]
  end

  defp dl_init_matrix(s_len, t_len) do
    for i <- 0..s_len, into: %{} do
      {i,
       for j <- 0..t_len, into: %{} do
         cond do
           i == 0 -> {j, j}
           j == 0 -> {j, i}
           true -> {j, 0}
         end
       end}
    end
  end

  defp dl_cell(d, s_chars, t_chars, i, j) do
    sc = Enum.at(s_chars, i - 1)
    tc = Enum.at(t_chars, j - 1)
    cost = if sc == tc, do: 0, else: 1

    val = min(min(d[i - 1][j] + 1, d[i][j - 1] + 1), d[i - 1][j - 1] + cost)
    maybe_transposition(d, s_chars, t_chars, i, j, val)
  end

  defp maybe_transposition(d, s_chars, t_chars, i, j, val) when i > 1 and j > 1 do
    if Enum.at(s_chars, i - 1) == Enum.at(t_chars, j - 2) and
         Enum.at(s_chars, i - 2) == Enum.at(t_chars, j - 1) do
      min(val, d[i - 2][j - 2] + 1)
    else
      val
    end
  end

  defp maybe_transposition(_d, _s_chars, _t_chars, _i, _j, val), do: val
end
