defmodule Tymeslot.Workers.SyncDebugCalendarWorker do
  @moduledoc """
  Oban worker that syncs a `debug` calendar integration into the local event
  cache.

  The debug provider reads from the in-memory `DebugStore` (the source of truth
  shared with booking availability and the interactive dev calendar), so a sync
  simply lists the store's events for a window, normalises them to
  `CalendarEvent` structs, and upserts them via `Sync.persist_normalised_events/2`.
  This makes events created through the dashboard grid — or generated by the
  recurring pattern/rules — appear in the calendar grid cache, and keeps the
  grid in step with the booking page.

  Dev/test only: the debug provider returns no client config outside `:dev`/
  `:test`, so a sync in production is a no-op.
  """

  use Oban.Worker, queue: :calendar_integrations, max_attempts: 1

  require Logger

  alias Tymeslot.Integrations.Calendar.CalendarIntegrationQueries
  alias Tymeslot.Integrations.Calendar.DebugCalendarProvider
  alias Tymeslot.Integrations.Calendar.Sync
  alias Tymeslot.Integrations.Calendar.SyncBroadcast

  # Window synced into the cache: a week back, two months forward.
  @past_days 7
  @future_days 60

  @impl Oban.Worker
  def perform(%Oban.Job{args: %{"calendar_integration_id" => integration_id}}) do
    case CalendarIntegrationQueries.get(integration_id) do
      {:ok, integration} ->
        sync(integration)

      {:error, :not_found} ->
        Logger.warning("Debug integration not found, discarding sync job",
          calendar_integration_id: integration_id
        )

        {:discard, "Integration not found"}

      {:error, :requires_reencryption, _integration} ->
        {:discard, "Integration requires re-encryption"}
    end
  end

  defp sync(integration) do
    case DebugCalendarProvider.build_client_configs(integration) do
      [client | _rest] ->
        do_sync(integration, client)

      [] ->
        Logger.debug("Debug provider returned no client config; skipping sync",
          calendar_integration_id: integration.id
        )

        :ok
    end
  end

  defp do_sync(integration, client) do
    now = DateTime.utc_now()
    start_time = DateTime.add(now, -@past_days, :day)
    end_time = DateTime.add(now, @future_days, :day)

    with {:ok, raw_events} <-
           DebugCalendarProvider.list_events(client, start_time: start_time, end_time: end_time),
         context = %{
           calendar_integration_id: integration.id,
           provider_calendar_id: "default",
           synced_at: now
         },
         {:ok, events} <- DebugCalendarProvider.normalise_events(raw_events, context),
         :ok <- Sync.persist_normalised_events(integration, events) do
      mark_synced(integration)

      # Signal the connected grid that this integration's sync cycle is done, so
      # the refresh spinner clears immediately. Without this the LiveView only
      # resets via its 30-second fallback timer, making the refresh appear to
      # hang. (The cache-update broadcast that reloads events is already emitted
      # inside `Sync.persist_normalised_events/2`.)
      SyncBroadcast.broadcast_sync_complete(integration.user_id, integration.id)
      :ok
    end
  end

  defp mark_synced(integration) do
    case CalendarIntegrationQueries.update_sync_state(integration, %{
           last_external_sync_at: DateTime.utc_now(:second)
         }) do
      {:ok, _updated} ->
        :ok

      {:error, changeset} ->
        Logger.warning("Failed to persist debug sync state",
          calendar_integration_id: integration.id,
          error: inspect(changeset)
        )

        :ok
    end
  end
end
